### ISSUE TITLE
[MOD] Glowing Star Bottle Cap

### ISSUE THREAD

**Issue by TDarkShadow** [VivaNewVegas/vivanewvegas.github.io#13]
## What is the name of mod?

Glowing Star Bottle Cap

## What kind of mod is it?

Makes the Sunset Sarsaparilla Star Bottle Caps glowing to be more noticable.

## The link of the mod

https://www.nexusmods.com/newvegas/mods/37355/

## Any additional context

[Screenshots](https://www.nexusmods.com/newvegas/mods/37355/?tab=images)

**Comment by VivaNewVegas** [comment]
not a fan of 'cheat' mods
