### ISSUE TITLE
[SUGGESTION] Add sanity checks

### ISSUE THREAD

**Issue by TDarkShadow** [VivaNewVegas/vivanewvegas.github.io#14]
## Is your feature request related to a problem?

When misreading something, it is usually minimal to fix, but very difficult or time-consuming to do when you're halfway through the guide.

## Explain the solution you'd like to see

Add checks (a set of instructions) or screenshots how a mod or tool installation should look like.

## Additional context

Inspired by Discord user Jszak16#1458 (and many before him).

**Comment by VivaNewVegas** [comment]
added them to the first instance of "Hide the following:" telling the reader to go back to the section where its explained if they dont know how. Will do more if you have any suggestions for common problems that could be fixed with a sanity check

**Comment by VivaNewVegas** [comment]
forgot to close this
