### ISSUE TITLE
[MOD] 

### ISSUE THREAD

**Issue by Omen267901** [VivaNewVegas/vivanewvegas.github.io#16]
## What is the name of mod?

New Vegas Roads Reborn

## What kind of mod is it?

This mod was intended to be an overhaul of most of the long stretches of empty road in FNV, but it was never completed. As it stands, it overhauls the areas around Nipton and Sloan.

## Known Issues
The new vehicle props added by the mod cannot be searched. (I forget what mod that feature is from)

Needs to be checked for performance, no known issues about it but it's always a possibility.

BE SURE TO INCLUDE https://www.nexusmods.com/newvegas/mods/68123, WHICH FIXES THE FACT THAT THE BASE MOD HAS 5 .ESPS

## The link of the mod

https://www.nexusmods.com/newvegas/mods/63075

## Any additional context

This mod is included in the Wabbajack version of Viva New Vegas, but is absent from the manual guide. The main purpose of this Issue is parity between the two, so feel free to go the other way with this if you work that out instead.

**Comment by Omen267901** [comment]
Discussion in the discord has determined that the better course of action will most likely be to remove the mod from the Wabbajack due to issues with the mod.

**Comment by VivaNewVegas** [comment]
talked about on discord
