### ISSUE TITLE
[MINOR MOD] Simple Assassin Suit Recolor

### ISSUE THREAD

**Issue by Omen267901** [VivaNewVegas/vivanewvegas.github.io#17]
## What is the name of mod?

Simple Assassin Suit Recolor

## What kind of mod is it?

Removes the purple shading on the upper body and gloves of the Assassin Suit. The Assassin Suit is a strange shade of purple in vanilla, making it not mesh well with other armor pieces and generally looking slightly out of place.

## Known Issues

None.

## The link of the mod
https://www.nexusmods.com/newvegas/mods/68323

## Any additional context

Likely fits best in Visuals - Optional. Some users may like the purple.

**Comment by VivaNewVegas** [comment]
too minor of a mod for me, especially since its a unique a piece of armor that youll pretty much never see because youll either be wearing it or itll be stored away. also the original coloring doesnt bother me
