### ISSUE TITLE
[MOD] LSO - A Lightweight Strip Overhaul

### ISSUE THREAD

**Issue by Omen267901** [VivaNewVegas/vivanewvegas.github.io#18]
## What is the name of mod?

LSO - A Lightweight Strip Overhaul

## What kind of mod is it?

A lightweight update to the Strip to clean it up, repair the roads, and clean up a lot of the dirtier textures on the main strip and in the casinos. Is compatible with casino overhauls, as it only changes textures which can be easily overwritten if needed.

## The link of the mod

https://www.nexusmods.com/newvegas/mods/65665

## Any additional context

This mod is included in the Wabbajack version of the guide, so this Issue exists mostly to reacquire parity between the two.

If included, the No Walls version should be used, as the main version has a minor oversight. The walls are stone from inside the Strip, but junk from outside.

Likely fits best in Visuals - Optional.

**Comment by VivaNewVegas** [comment]
it doesnt change the textures (doesnt even have a textures folder), it marks the stains and cars or whatever as initially disabled, so it does need compatibiltiy patches

**Comment by VivaNewVegas** [comment]
i also dont really like the interior changes at all, the casinos should be pretty dirty and grimy as it adds to the atmosphere and makes more sense than them being crystal clean. the exterior changes are nice tho
