### ISSUE TITLE
[MINOR MOD] Pip-Boy Counters For Rads And Hardcore Needs

### ISSUE THREAD

**Issue by Omen267901** [VivaNewVegas/vivanewvegas.github.io#19]
## What is the name of mod?

Pip-Boy Counters For Rads And Hardcore Needs

## What kind of mod is it?

Adds a Clock, Rad Counter, and tickers for the Hardcore Needs to the side of the pip-boy. Compatible with the popular pip-boy replacers.

## The link of the mod

https://www.nexusmods.com/newvegas/mods/62364

## Any additional context

Recommends using with https://www.nexusmods.com/newvegas/mods/54609/? . I don't see why it would have an issue with our current Pip Boy retexture, but it needs checked.

Likely fits best in Gameplay - Optional. Extended HUD is already capable of this functionality, but some users may prefer this approach.

**Comment by TDarkShadow** [comment]
I wouldn't add this myself. It looks like using LCD screens which is not lore-friendly.

**Comment by VivaNewVegas** [comment]
looks way too out of place

**Comment by VivaNewVegas** [comment]
also its easier and better looking to just use oHUD for that info
