### ISSUE TITLE
New Vegas Load Order question

### ISSUE THREAD

**Issue by kronikpillow** [VivaNewVegas/vivanewvegas.github.io#22]
the New Vegas Load Order.txt includes esp's that are not in the guide like:

CardMaster.esm
CardMaster DM.esp
Occlusion.esp
Glasses Fix.esp
Inventory Search.esp 

only one I haven't figured out is the Glasses Fix.esp ... from which mod does this come? thanks

**Comment by TDarkShadow** [comment]
The load order txt file list all mods you install with the guide, including the optional mods.
@VivaNewVegas usually also leave mod plugins in it, after they get removed from the guide for transparency or if the mods get included back in the future.

As for your question, the Glasses Fix.esp is from the [Any glasses with any mask](https://www.nexusmods.com/newvegas/mods/66321) mod.

**Comment by kronikpillow** [comment]
I don't quite understand why you closed my topic, the further i dug in to the guide the more messy it became regarding plugins and mods, there seem to be actually quite a lot that are not in the guide ... am I supposed to follow the guide or the load order? and if I'm supposed to follow the load order then I have quite a few questions regarding mods

**Comment by Fooughhy** [comment]
> @VivaNewVegas usually also leave removed mod plugins in it, after they get removed from the guide, for transparency or if the mods get included back in the future.

I believe he did answer your question. The load order would still be correct, even if mods are removed from the guide.

**Comment by TDarkShadow** [comment]
Because your original question was answered but if you think the issue is not resolved, I'll reopen it.
You're supposed to follow the guide. It also explain why the load orders are necessary to use.
If you have more questions, go ahead and ask them in this issue, or go to [our Discord server](https://discord.gg/DhX5S27) for more information.

**Comment by TDarkShadow** [comment]
@kronikpillow came to the Discord server and is being helped.
This issue is now closed and locked.
