### ISSUE TITLE
[BUG] Optionnal mods aren't in every loadorder.txt

### ISSUE THREAD

**Issue by TheFrenchGhosty** [VivaNewVegas/vivanewvegas.github.io#24]
## Describe the bug

I started the guide (thanks for making it by the way) and installed some of the optionnal bugfix from https://vivanewvegas.github.io/core-optionalbugfixes.html they were in the loadorder.txt of the "Core".

However after I imported the "Visual" loadorder.txt I noticed that they ended up at the end, after checking the file, they're actually not in it.

Is that an oversight? Why is the "Core" loadorder.txt not used for the "Visual" one, and the "Visual" one not used for the Gameplay (and so on).

**Comment by TDarkShadow** [comment]
That's because the optional bugfixes can (and should) be merged within the Core Merge file you create at the Core - Finish line.

The loadorder files are also different from every module to make it easier and transparent in case of updates.

**Comment by TheFrenchGhosty** [comment]
Oh my bad, I forgot to merge them.
