### ISSUE TITLE
[MOD] Moburma80 series "New Vegas Uncut"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [VivaNewVegas/vivanewvegas.github.io#26]
## What is the name of mod?

New Vegas Uncut

## What kind of mod is it?

Series of mod that restore cut content, they should all be safe except freeside open.

## The link of the mod

https://www.nexusmods.com/newvegas/users/3010984?tab=user+files

## Any additional context

I'm really curious as to why they aren't already included.

**Comment by TDarkShadow** [comment]
A variety of reasons, like some of them aren't well made or you will never notice them during regular gameplay.
Mods like [Uncut Wasteland](https://www.nexusmods.com/newvegas/mods/56625) and [The Living Desert](https://www.nexusmods.com/newvegas/mods/64623) already adds some of the cut content back aswell.

**Comment by TheFrenchGhosty** [comment]
Good to know, thanks.
