### ISSUE TITLE
[SUGGESTION] "NMC's Texture Pack" main menu logo should be hidden

### ISSUE THREAD

**Issue by TheFrenchGhosty** [VivaNewVegas/vivanewvegas.github.io#27]
## Is your feature request related to a problem?

NMC's Texture Pack include a new main_title.dds, the issue is that this title mention that it's from NMC.

## Explain the solution you'd like to see

The guide should either say that it needs to be hidden, or it should be overwritten by a better main menu mod (or an edited version that remove this text).

## Additional context

![main_title](https://user-images.githubusercontent.com/47571719/89578208-53d1cc00-d821-11ea-9081-cfa9f25be3d4.png)

**Comment by TDarkShadow** [comment]
This will be taken care of by @VivaNewVegas with the use of some additional optional mods, in the near feature.
Thank you for your suggestion.

**Comment by VivaNewVegas** [comment]
Yeah, I'm planning on using these two:
https://www.nexusmods.com/newvegas/mods/65841
https://www.nexusmods.com/newvegas/mods/64931
