### ISSUE TITLE
[MOD] A retexture for the Pimp-Boy 3 Billion	

### ISSUE THREAD

**Issue by TheFrenchGhosty** [VivaNewVegas/vivanewvegas.github.io#28]
## What is the name of mod?

Any mod that retexture the Pimp-Boy 3 Billion.

## What kind of mod is it?

The Pimp-Boy 3 Billion	 looks really bad compared to the Pip-Boy, a retexture is really needed. However there doesn't seem to be a lot of them.

## The link of the mod

https://www.nexusmods.com/newvegas/mods/60629 maybe?

**Comment by VivaNewVegas** [comment]
Good idea, I'll add one to the upcoming optional visuals section
