### ISSUE TITLE
Possible typo in instructions? (AVX2 vs SSE2)

### ISSUE THREAD

**Issue by jwarner112** [VivaNewVegas/vivanewvegas.github.io#31]
In the New Vegas Heap Replacer section of the Utilities page, you [you have a line that reads][typo]:

> If you have an older CPU (pre-2013), use the **Main File - NVHR - AVX2 2.4 SSE2** instead.

I interpreted this to mean "Use the version compiled for the SSE2 instruction set", but the wording and use of the term `AVX2` made it seem like a copy/paste error that might be confusing. If I'm wrong, ignore me on this but I figured I'd mention it. I'm issuing a PR to accept it in the event that I'm correct that it was a typo.

Thanks for this guide by the way, helping me NOT spend two weeks to get a half-stable build together!

[typo]: https://github.com/VivaNewVegas/vivanewvegas.github.io/blob/4cbc7ead606c7492b3875bb40f1507254bdedc4a/utilities.html#L122

**Comment by VivaNewVegas** [comment]
fixed, thanks
