### ISSUE TITLE
[SUGGESTION] Patch for JSUE changing Varmint Rifle ammo back to 5.56mm

### ISSUE THREAD

**Issue by Tea23** [VivaNewVegas/vivanewvegas.github.io#33]
## Is your feature request related to a problem?

JSawyer Ultimate Edition, which VNV now suggests using, replaces the Varmint Rifle's ammo type with .22LR. This goes explicitly against Josh's design - see his posts on SomethingAwful where he confirms this https://forums.somethingawful.com/showthread.php?noseen=0&threadid=3439576&pagenumber=1093&perpage=40#post512404421

I have attached an esp that changes the Varmint Rifle and Ratslayers' ammo types with 5.56mm, and also makes sure the leveled list for them is set correctly to 5.56mm. Without this patch, JSUE can conflict with other mods (like WMX), causing Varmint Rifles to be distributed with .22LR ammo but requiring 5.56.

[jsue.zip](https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/files/5983987/jsue.zip)

## Explain the solution you'd like to see

I would recommend adding a note to the guide suggesting this patch for players who wish to keep the original design of the rifles. It of course needs to be added into the load order AFTER JSUE.

**Comment by TDarkShadow** [comment]
I've assigned Qolore so he can share his thoughts on it.
As for your argument, WMX isn't compatible anyway, like most mods that adds weapon mods, with the Weapon Mesh Improvement Mod.

**Comment by Tea23** [comment]
Good point, I don't actually run WMX anymore so I'm not actually sure which mod caused the list to get screwed with. At any rate, the .22LR change is PushTheWinButton second guessing JSawyer's choices as well as early game feedback. Definitely recommended for purists!

**Comment by VivaNewVegas** [comment]
even if it isn't what Sawyer intended, I think its much more balanced. prevents the player from having loads of 5.56 by the time they get That Gun or something similar and just being able to rely it on for pretty much the rest of the gane
