### ISSUE TITLE
[SUGGESTION] When should I update manually-added mods?

### ISSUE THREAD

**Issue by NekoAlosama** [VivaNewVegas/vivanewvegas.github.io#38]
## Is your feature request related to a problem?

There are some manually-added mods that are updated pretty frequently, like xNVSE and some patches in [the patch emporium](https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/commits/main). For me, the reason I don't play the game that much is because I don't want to spend the time checking for these updates and applying them to make sure my game is stable. I'm mainly wondering a) when should I update any of the mods and b) how do I keep track of updated mods that have to be manually added.

## Explain the solution you'd like to see

I don't know if there's a way to fix this aside from always checking GitHub and Nexus to look for updates. As far as I know, there isn't a manual way for MO2 to check for updates in manually-added mods.

**Comment by TDarkShadow** [comment]
Nope, there is no way to have MO2 or other tools (atm) to check for updates from manually added mods.
MO2 does have a functionality to check for updates of Nexus added mods.
![afbeelding](https://user-images.githubusercontent.com/5389859/133300122-b0b99985-7f27-4300-af38-216214828942.png)
As for the updating mods, you can check the git commits or the changelog (which fair, we don't update as frequently unless there are some major changes).

**Comment by NekoAlosama** [comment]
Gotcha.  One thing I am wondering is if the guide intends you to have the mods be updated whenever you want or when you encounter bugs, or have them always be updated before starting up the game.

**Comment by VivaNewVegas** [comment]
depends on the mod, usually if you have a perfectly working setup you shouldn't worry about updating - but usually NVSE-adjacent stuff will always be safe

**Comment by NekoAlosama** [comment]
> 
> 
> depends on the mod, usually **if you have a perfectly working setup you shouldn't worry about updating - but usually NVSE-adjacent stuff will always be safe**

That's all of the questions I had. My only suggestion would be to at least say something along those lines in the guide, for the people who do worry.

**Comment by NekoAlosama** [comment]
> depends on the mod, usually **if you have a perfectly working setup you shouldn't worry about updating - but usually NVSE-adjacent stuff will always be safe**

I still have no idea how I or you would want to word this in the guide.
