### ISSUE TITLE
[MOD] Improved Lighting Shaders

### ISSUE THREAD

**Issue by emoose** [VivaNewVegas/vivanewvegas.github.io#39]
## What is the name of mod?

Improved Lighting Shaders

## What kind of mod is it?

Graphical enhancement, fixing the lighting bug that can happen in exteriors with many light sources (not very noticeable in vanilla, but modded games usually add a lot more lights that make the bug much more obvious)

## The link of the mod

https://www.nexusmods.com/newvegas/mods/69833

## Any additional context

Hi there, I'm the dev of ILS, I noticed it was featured in an older Viva New Vegas guide but seems it got removed during a redesign, just wondering is there any reason for it being removed?

Almost all the latest comments on NexusMods have been positive about it, other than ENB/NV Reloaded incompatibility (which VNV doesn't seem to use anyway) the only reported issue hasn't been reproducible for me, and my requests on NM for anyone to let me know of any other incompatibilities has been unanswered, leaving me to believe there's no other issues around it (though if you know of any please let me know!)

Besides incompatibilities, was it maybe removed because another mod has replaced it? If any other mod has been made that fixes the same thing/integrates this fix with a larger fix pack I might have missed it.

Anyway, thanks for reading
emoose (stoker25)

**Comment by VivaNewVegas** [comment]
Finally updated the guide with ILS included :)
