### ISSUE TITLE
[SUGGESTION] Document changes with FAQ and Resources

### ISSUE THREAD

**Issue by NekoAlosama** [VivaNewVegas/vivanewvegas.github.io#41]
## Is your feature request related to a problem?

I think that changes to the Frequently-Asked Questions, Tools to Avoid, Mods to Avoid, and LOD Generation Guide pages should be documented in the Changelog. This more applies to the Mods to Avoid section, since that was where I noticed a few changes like added performance notes to the Vault 22 Overhaul Remastered and New Vegas Landscape Overhaul Re-Remastered mods and the removal of PerkPackPlus as a replacement for the More Perks mod (though this is probably because PPP has bugs of its own).

## Explain the solution you'd like to see

Start including edits to these above pages into the Changelog. In the 10/30/21 update, the Mods to Avoid page is the only one with [notable edits](https://github.com/VivaNewVegas/vivanewvegas.github.io/commit/b2dbfbd8e719ef9fb74bd0bc7e3525b35d218caf#diff-4f7b8881246cc885abfd3882d5f9beaa6d3e8e88b5105f99ba8b31b4180494f8). while the rest got the same update to include the Tweaks and Content pages.

**Comment by NekoAlosama** [comment]
@TDarkShadow @VivaNewVegas

**Comment by pippaine** [comment]
Alternatively, commits could include messages more descriptive than these:

![image](https://user-images.githubusercontent.com/72939111/185726003-9b6cd931-f359-47f4-8815-2d8292d6a398.png)

[How to Write a Git Commit Message](https://cbea.ms/git-commit/#intro)

Commit history can act as a changelog in and of itself, and help people who are trying to update their previously-existing Viva New Vegas installations (#38) without having to start from scratch.

**Comment by VishVadeva50** [comment]
No

**Comment by NekoAlosama** [comment]
@pippaine Unfortunately, not all of the commits since this issue was closed by @VishVadeva50  are properly descriptive.
