### ISSUE TITLE
not recomended tools

### ISSUE THREAD

**Issue by Pockets-byte** [VivaNewVegas/vivanewvegas.github.io#87]
in the not recomended tools, two very powerful (still worked on)staples are very strongly discouraged. wyre bash is a powerful and robust mod manager that works on all creation engine games, and is highly customizable and multifunction, with optional automation features, and excellent handling of multiple files. the automation the guide talks about is minimal and can be removed with a single option as stated clearly in the manual. Loot is a staple of bethesda modding, very powerful, and most of all, customizable, making it quite easy for people who dislike automation to create their own load orders to then distribute

**Comment by VishVadeva50** [comment]
Cool story
