### ISSUE TITLE
[Bugfix] Fix for overblown sunglare issue

### ISSUE THREAD

**Issue by Omen267901** [VivaNewVegas/vivanewvegas.github.io#9]
Users on this discord have been consistently reporting an issue with Nevada Skies' sunglare where it takes up sometimes over a quarter of the entire screen. The bug was pretty quickly determined to be a conflict and not NS itself, but we were puzzled for a while. We got it figured out today though, thanks to Anro's help.

The problem mod is EXE, Effect teXtures Enhanced. It also has a nv_sunglare.dds, and they seem to stack somehow, causing [this monstrosity of a screen-block](https://cdn.discordapp.com/attachments/451522713014501386/658181570749792276/unknown.png)

By simply hiding the nv_sunglare.dds in EXE,  [found here](https://i.imgur.com/ZMIhYqZ.png), you can fix the issue. This causes the sun to look correct and not obscure a huge chunk of your screen.

**Comment by TDarkShadow** [comment]
> By simply hiding the nv_sunglare.dds in EXE, found here `[https://i.imgur.com/ZMIhYqZ.png](url)`.
Wrong syntax, and you don't necessarily have to type it, but you probably meant to type it as `[found here](https://i.imgur.com/ZMIhYqZ.png)` ?

**Comment by Omen267901** [comment]
> 
> 
> > By simply hiding the nv_sunglare.dds in EXE, found here `[https://i.imgur.com/ZMIhYqZ.png](url)`.
> 
> Wrong syntax, and you don't necessarily have to type it, but you probably meant to type it as `[found here](https://i.imgur.com/ZMIhYqZ.png)` ?

Fixed, thank you. I don't use github a ton.
